#!/usr/bin/env python3
"""
Reconcile numbers between data files and paper tex files.

Reads all authoritative data sources (bootstrap CIs, behavioral JSONs,
probe results, transfer matrices) and:
  1. Produces results/canonical_numbers.json with THE single source of truth.
  2. Scans the paper tex file and reports every mismatch.

The key methodology distinction:
  - Original pipeline: 5-fold CV on 330 items (7 categories, 165 pairs).
    Peak layers: Llama L14 (AUC=0.999), R1-Distill L16 (AUC=0.985).
  - Bootstrap pipeline: 1000-resample bootstrap on 160 vulnerable items
    (80 conflict / 80 no-conflict from 3 vulnerable categories).
    Peak layers: Llama L16 (AUC=0.974), R1-Distill L31 (AUC=0.930).
  - Cross-prediction was done at L14 (original pipeline peak).

For the paper: bootstrap CIs are the correct numbers for the main claims
because they come with proper uncertainty quantification. The 5-fold CV
numbers appear in the supplementary layer-by-layer tables.

Usage:
    python scripts/reconcile_numbers.py
"""
from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results"
PAPER_TEX = ROOT / "paper" / "workshop_paper_anonymous.tex"
SUPP_TEX = ROOT / "paper" / "supplementary.tex"
CANONICAL_OUT = RESULTS / "canonical_numbers.json"

BOOTSTRAP_FILES = {
    "llama": RESULTS / "bootstrap_cis" / "unsloth_Meta-Llama-3.1-8B-Instruct_bootstrap_cis.json",
    "r1_distill": RESULTS / "bootstrap_cis" / "deepseek-ai_DeepSeek-R1-Distill-Llama-8B_bootstrap_cis.json",
    "olmo_instruct": RESULTS / "bootstrap_cis" / "allenai_OLMo-3-7B-Instruct_bootstrap_cis.json",
    "olmo_think": RESULTS / "bootstrap_cis" / "allenai_OLMo-3-7B-Think_bootstrap_cis.json",
}

BEHAVIORAL_470 = RESULTS / "summary" / "behavioral_470_complete.json"
BEHAVIORAL_7CAT = RESULTS / "summary" / "behavioral_complete.json"

CV_PROBE_FILES = {
    "llama_all": RESULTS / "probes" / "llama31_ALL_layer_aucs.json",
    "r1_distill_all": RESULTS / "probes" / "r1_distill_ALL_layer_aucs.json",
}

CROSS_PRED_FILES = {
    "llama": RESULTS / "probes" / "llama_cross_prediction.json",
    "r1_distill": RESULTS / "probes" / "r1_distill_cross_prediction.json",
}

TRANSFER_MATRIX_FILE = RESULTS / "probes" / "transfer_matrix_l14_llama.json"
CROSS_MODEL_FILE = RESULTS / "probes" / "cross_model_transfer_llama_r1.json"
LURE_SUSCEPT_FILES = {
    "llama": RESULTS / "behavioral" / "llama31_lure_susceptibility.json",
    "r1_distill": RESULTS / "behavioral" / "r1_distill_lure_susceptibility.json",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def load_json(path: Path) -> dict:
    with open(path) as f:
        return json.load(f)


def find_peak(layers: list[dict], key: str = "auc") -> dict:
    """Return the layer dict with the highest value for `key`."""
    return max(layers, key=lambda x: x[key])


def round3(v: float) -> float:
    return round(v, 3)


def round4(v: float) -> float:
    return round(v, 4)


# ---------------------------------------------------------------------------
# 1. Build canonical numbers from authoritative data sources
# ---------------------------------------------------------------------------
def build_canonical() -> dict[str, Any]:
    """Build the single authoritative set of numbers."""
    canonical: dict[str, Any] = {
        "_metadata": {
            "description": (
                "Canonical numbers for the s1s2 paper. "
                "Generated by scripts/reconcile_numbers.py. "
                "All claims in the paper and supplementary MUST match these values."
            ),
            "methodology_note": (
                "Bootstrap numbers (peak_bootstrap) come from 1000-resample bootstrap "
                "on 160 vulnerable items (80 conflict / 80 no-conflict). "
                "CV numbers (peak_cv) come from 5-fold stratified CV on 330 items "
                "(7 categories, 165 pairs). Both are real; the paper uses bootstrap "
                "for main claims (with CIs) and CV for supplementary layer tables. "
                "Cross-prediction was done at L14 (CV peak)."
            ),
        },
        "behavioral": {},
        "probes_bootstrap": {},
        "probes_cv": {},
        "cross_prediction": {},
        "transfer_matrix": {},
        "cross_model_transfer": {},
        "lure_susceptibility": {},
    }

    # ---- Behavioral data ----
    # IMPORTANT: The paper uses DIFFERENT data sources for different numbers:
    #   - Overall rates (27.3%, 2.4%): from _ALL raw files (7 categories, 165 pairs)
    #   - Per-category rates (original 7): from _ALL raw files
    #   - Per-category rates (4 new cats): from 470-item data
    #   - Qwen overall (21%, 7%): from behavioral_complete (7 categories, 165 pairs)
    #   - OLMo: from 470-item data (only dataset for OLMo)
    # behavioral_complete.json has a MIX: Llama/R1 have 8 cats (190 pairs),
    #   Qwen has 7 cats (165 pairs), OLMo has 11 cats (235 pairs).
    #   The paper's overall rates do NOT match behavioral_complete for Llama/R1.

    beh_complete = load_json(BEHAVIORAL_7CAT)
    beh_470 = load_json(BEHAVIORAL_470)

    # Raw _ALL files: the TRUE source for the paper's headline Llama/R1 rates
    for mk, path, display in [
        ("llama", RESULTS / "behavioral" / "llama31_8b_ALL.json", "Llama-3.1-8B"),
        ("r1_distill", RESULTS / "behavioral" / "r1_distill_llama_ALL.json", "R1-Distill-8B"),
    ]:
        raw = load_json(path)
        results = raw["results"]
        n_conflict = sum(1 for r in results if r["conflict"])
        n_lure = sum(1 for r in results if r["conflict"] and r["verdict"] == "lure")
        canonical["behavioral"][mk] = {
            "display_name": display,
            "overall_7cat_raw": {
                "n_conflict": n_conflict,
                "n_lure": n_lure,
                "lure_rate": round4(n_lure / n_conflict),
                "lure_rate_pct": round(n_lure / n_conflict * 100, 1),
                "source": f"_ALL raw file ({n_conflict} conflict items, 7 categories)",
            },
        }

    # Qwen overall rates from behavioral_complete (7-cat subset, 165 pairs)
    for mk in ["qwen_nothink", "qwen_think"]:
        if mk in beh_complete["models"]:
            info = beh_complete["models"][mk]
            canonical["behavioral"][mk] = {
                "display_name": info["display_name"],
                "overall_7cat_raw": {
                    "n_conflict": info["overall"]["n_conflict"],
                    "n_lure": info["overall"]["n_lure"],
                    "lure_rate": round4(info["overall"]["lure_rate"]),
                    "lure_rate_pct": round(info["overall"]["lure_rate"] * 100, 1),
                    "source": "behavioral_complete (7 categories)",
                },
            }

    # Also store behavioral_complete overall for reference (may differ from raw)
    for mk, info in beh_complete["models"].items():
        if mk in canonical["behavioral"]:
            canonical["behavioral"][mk]["overall_beh_complete"] = {
                "n_conflict": info["overall"]["n_conflict"],
                "n_lure": info["overall"]["n_lure"],
                "lure_rate": round4(info["overall"]["lure_rate"]),
                "lure_rate_pct": round(info["overall"]["lure_rate"] * 100, 1),
            }

    # 470-item per-category rates (Table 1 in paper)
    for mk, info in beh_470["models"].items():
        if mk not in canonical["behavioral"]:
            canonical["behavioral"][mk] = {"display_name": info["display_name"]}
        canonical["behavioral"][mk]["overall_470"] = {
            "n_conflict": info["overall"]["n_conflict"],
            "n_lure": info["overall"]["n_lure"],
            "lure_rate": round4(info["overall"]["lure_rate"]),
            "lure_rate_pct": round(info["overall"]["lure_rate"] * 100, 1),
        }
        cats = {}
        for cat, cinfo in info["categories"].items():
            if cinfo is not None:
                cats[cat] = {
                    "n_conflict": cinfo["n_conflict"],
                    "n_lure": cinfo["n_lure"],
                    "lure_rate_pct": round(cinfo["lure_rate"] * 100, 0),
                }
        canonical["behavioral"][mk]["per_category_470"] = cats

    # OLMo behavioral from 470-item raw files (NOT from behavioral_complete which
    # may not have them)
    for olmo_key, olmo_path in [
        ("olmo_instruct", RESULTS / "behavioral" / "olmo3_instruct_ALL.json"),
        ("olmo_think", RESULTS / "behavioral" / "olmo3_think_ALL.json"),
    ]:
        raw = load_json(olmo_path)
        results = raw.get("results", [])
        overall_conflict = 0
        overall_lured = 0
        cats: dict[str, dict] = defaultdict(lambda: {"conflict": 0, "lured": 0})
        for item in results:
            if item.get("conflict", False):
                cat = item["category"]
                cats[cat]["conflict"] += 1
                overall_conflict += 1
                if item.get("verdict") == "lure":
                    cats[cat]["lured"] += 1
                    overall_lured += 1

        disp = "OLMo-3-7B-Instruct" if "instruct" in olmo_key else "OLMo-3-7B-Think"
        canonical["behavioral"][olmo_key] = {
            "display_name": disp,
            "overall_470": {
                "n_conflict": overall_conflict,
                "n_lure": overall_lured,
                "lure_rate": round4(overall_lured / overall_conflict) if overall_conflict else 0,
                "lure_rate_pct": round(overall_lured / overall_conflict * 100, 1) if overall_conflict else 0,
            },
            "per_category_470": {
                cat: {
                    "n_conflict": v["conflict"],
                    "n_lure": v["lured"],
                    "lure_rate_pct": round(v["lured"] / v["conflict"] * 100, 0) if v["conflict"] else 0,
                }
                for cat, v in sorted(cats.items())
            },
        }

    # ---- Bootstrap probe CIs (main paper claims) ----
    for model_key, path in BOOTSTRAP_FILES.items():
        data = load_json(path)
        model_info = {"model_hf": data["model"], "n_bootstrap": data["n_bootstrap"]}
        for cond_name, layers in data["conditions"].items():
            peak = find_peak(layers)
            ctrl = peak.get("control_auc")
            sel = peak.get("selectivity")
            model_info[f"peak_{cond_name}"] = {
                "layer": peak["layer"],
                "auc": round4(peak["auc"]),
                "ci_lower": round4(peak["ci_lower"]),
                "ci_upper": round4(peak["ci_upper"]),
            }
            if ctrl is not None:
                model_info[f"peak_{cond_name}"]["control_auc"] = round4(ctrl)
                model_info[f"peak_{cond_name}"]["selectivity"] = round4(sel)

            # Also store max control AUC across all layers
            if any("control_auc" in l for l in layers):
                max_ctrl_layer = max(
                    [l for l in layers if "control_auc" in l],
                    key=lambda x: x["control_auc"],
                )
                model_info[f"max_control_{cond_name}"] = {
                    "layer": max_ctrl_layer["layer"],
                    "control_auc": round4(max_ctrl_layer["control_auc"]),
                }

        canonical["probes_bootstrap"][model_key] = model_info

    # ---- 5-fold CV probes (supplementary layer tables) ----
    for model_key, path in CV_PROBE_FILES.items():
        data = load_json(path)
        canonical["probes_cv"][model_key] = {
            "best_layer": data["best_layer"],
            "best_auc": round4(data["best_auc"]),
            "categories": data.get("categories", "ALL"),
            "n_items": data.get("n_items"),
        }

    # ---- Cross-prediction (done at L14, original pipeline) ----
    for model_key, path in CROSS_PRED_FILES.items():
        data = load_json(path)
        layer_results = {}
        for layer_str, vals in data["results"].items():
            layer_results[int(layer_str)] = {
                "within_vulnerable": round4(vals["within_vulnerable"]),
                "transfer_to_immune": round4(vals["transfer_to_immune"]),
            }
        canonical["cross_prediction"][model_key] = {
            "model_name": data["model"],
            "layers": layer_results,
        }

    # ---- Transfer matrix (Llama, L14) ----
    tm = load_json(TRANSFER_MATRIX_FILE)
    canonical["transfer_matrix"] = {
        "model": "Llama",
        "layer": 14,
        "note": "Rows = train category, Cols = test category",
        "matrix": tm,
    }

    # ---- Cross-model transfer ----
    cm = load_json(CROSS_MODEL_FILE)
    for direction in ["llama_to_r1", "r1_to_llama"]:
        results = cm["results"][direction]
        peak = max(results, key=lambda x: x["auc"])
        canonical["cross_model_transfer"][direction] = {
            "peak_layer": peak["layer"],
            "peak_auc": round4(peak["auc"]),
        }

    # ---- Lure susceptibility ----
    for model_key, path in LURE_SUSCEPT_FILES.items():
        if path.exists():
            data = load_json(path)
            # Extract mean score
            if "mean_score" in data:
                canonical["lure_susceptibility"][model_key] = {
                    "mean": data["mean_score"],
                }
            elif "summary" in data:
                canonical["lure_susceptibility"][model_key] = data["summary"]
            else:
                canonical["lure_susceptibility"][model_key] = {
                    "keys": list(data.keys())[:10]
                }

    return canonical


# ---------------------------------------------------------------------------
# 2. Check paper tex against canonical numbers
# ---------------------------------------------------------------------------
class Mismatch:
    def __init__(
        self,
        inconsistency_id: int,
        severity: str,
        location: str,
        line: int | None,
        claim: str,
        canonical: str,
        fix: str,
    ):
        self.inconsistency_id = inconsistency_id
        self.severity = severity
        self.location = location
        self.line = line
        self.claim = claim
        self.canonical = canonical
        self.fix = fix

    def __str__(self) -> str:
        loc = f" (line {self.line})" if self.line else ""
        return (
            f"[#{self.inconsistency_id}] {self.severity} | {self.location}{loc}\n"
            f"  Paper says: {self.claim}\n"
            f"  Data says:  {self.canonical}\n"
            f"  Fix: {self.fix}"
        )


def check_paper(canonical: dict) -> list[Mismatch]:
    """Check the paper tex against canonical numbers."""
    mismatches: list[Mismatch] = []

    paper_text = PAPER_TEX.read_text()
    paper_lines = paper_text.split("\n")
    supp_text = SUPP_TEX.read_text() if SUPP_TEX.exists() else ""
    supp_lines = supp_text.split("\n") if supp_text else []

    def find_line(text: str, lines: list[str]) -> int | None:
        """Find the 1-indexed line number containing text."""
        for i, line in enumerate(lines):
            if text in line:
                return i + 1
        return None

    # ---- Bootstrap probe numbers ----
    llama_boot = canonical["probes_bootstrap"]["llama"]
    r1_boot = canonical["probes_bootstrap"]["r1_distill"]
    olmo_inst_boot = canonical["probes_bootstrap"]["olmo_instruct"]
    olmo_think_boot = canonical["probes_bootstrap"]["olmo_think"]

    llama_vuln = llama_boot["peak_vulnerable"]
    r1_vuln = r1_boot["peak_vulnerable"]

    # #1: Llama peak AUC and layer
    # Paper claims: 0.974 at L16 [0.952, 0.992]
    # Data: 0.9742 at L16 [0.9515, 0.9917] (bootstrap on vulnerable)
    # These are consistent (paper rounds to 3dp)
    paper_llama_auc = 0.974
    paper_llama_layer = 16
    data_llama_auc = llama_vuln["auc"]
    data_llama_layer = llama_vuln["layer"]

    if paper_llama_layer != data_llama_layer:
        mismatches.append(Mismatch(
            1, "CRITICAL", "Main paper (multiple locations)",
            find_line("0.974", paper_lines),
            f"Llama peak at L{paper_llama_layer}",
            f"Bootstrap peak at L{data_llama_layer}",
            f"Update peak layer to L{data_llama_layer}",
        ))

    if abs(paper_llama_auc - data_llama_auc) > 0.002:
        mismatches.append(Mismatch(
            1, "CRITICAL", "Main paper (multiple locations)",
            find_line("0.974", paper_lines),
            f"Llama peak AUC = {paper_llama_auc}",
            f"Bootstrap peak AUC = {data_llama_auc:.4f} (rounds to {round3(data_llama_auc)})",
            f"Update AUC to {round3(data_llama_auc)}",
        ))

    # Supplementary says L14 peak with AUC=0.999 -- that's from the CV pipeline
    # Both are correct but from different methodologies
    cv_llama = canonical["probes_cv"]["llama_all"]
    mismatches.append(Mismatch(
        1, "MODERATE", "Supplementary Table C.1 vs. main paper",
        None,
        (f"Supplementary bolded L{cv_llama['best_layer']} as peak "
         f"(AUC={cv_llama['best_auc']:.4f}, 5-fold CV on 330 items)"),
        (f"Main paper uses L{data_llama_layer} "
         f"(AUC={data_llama_auc:.4f}, bootstrap on 160 vulnerable items)"),
        ("Both are real. Supplementary should clarify it shows 5-fold CV values, "
         "not bootstrap. Add a note: 'AUC values are 5-fold CV means; bootstrap "
         "CIs in the main text use a different resampling procedure.'"),
    ))

    # #2: R1-Distill peak AUC and layer
    paper_r1_auc = 0.930
    paper_r1_layer = 31
    data_r1_auc = r1_vuln["auc"]
    data_r1_layer = r1_vuln["layer"]

    if paper_r1_layer != data_r1_layer:
        mismatches.append(Mismatch(
            2, "CRITICAL", "Main paper (multiple locations)",
            find_line("0.930", paper_lines),
            f"R1-Distill peak at L{paper_r1_layer}",
            f"Bootstrap peak at L{data_r1_layer}",
            f"Update peak layer to L{data_r1_layer}",
        ))

    if abs(paper_r1_auc - data_r1_auc) > 0.002:
        mismatches.append(Mismatch(
            2, "CRITICAL", "Main paper (multiple locations)",
            find_line("0.930", paper_lines),
            f"R1-Distill peak AUC = {paper_r1_auc}",
            f"Bootstrap peak AUC = {data_r1_auc:.4f} (rounds to {round3(data_r1_auc)})",
            f"Update AUC to {round3(data_r1_auc)}",
        ))

    # Supplementary says L14=0.929 as peak (CV pipeline)
    cv_r1 = canonical["probes_cv"]["r1_distill_all"]
    mismatches.append(Mismatch(
        2, "MODERATE", "Supplementary Table C.1 vs. main paper",
        None,
        (f"Supplementary bolded L{cv_r1['best_layer']} as peak "
         f"(AUC={cv_r1['best_auc']:.4f}, 5-fold CV)"),
        (f"Main paper uses L{data_r1_layer} "
         f"(AUC={data_r1_auc:.4f}, bootstrap on 160 vulnerable items)"),
        ("Same methodology difference as Llama. "
         "Supplementary should clarify it shows 5-fold CV, not bootstrap."),
    ))

    # #3: Behavioral lure rate mismatches
    # Main paper Table 1 uses DIFFERENT data sources for different numbers:
    #   - Overall rates (27.3%, 2.4%, 21.0%, 7.0%): from 7-cat subset (330 items)
    #   - Per-category rates for original 7 categories: from 7-cat raw files
    #   - Per-category rates for 4 new categories: from 470-item data
    #   - OLMo per-category rates: from 470-item data (only dataset for OLMo)
    # We must compare against the CORRECT source for each number.

    ORIGINAL_7_CATS = {"crt", "base_rate", "conjunction", "syllogism",
                       "arithmetic", "framing", "anchoring"}
    NEW_4_CATS = {"loss_aversion", "sunk_cost", "certainty_effect", "availability"}

    # Load 7-category raw behavioral data for ground truth comparison
    beh_7cat_raw: dict[str, dict[str, int]] = {}
    for mk, path in [
        ("llama", RESULTS / "behavioral" / "llama31_8b_ALL.json"),
        ("r1_distill", RESULTS / "behavioral" / "r1_distill_llama_ALL.json"),
    ]:
        raw = load_json(path)
        cats_data: dict[str, dict[str, int]] = defaultdict(lambda: {"conflict": 0, "lured": 0})
        for item in raw["results"]:
            if item.get("conflict", False):
                cat = item["category"]
                cats_data[cat]["conflict"] += 1
                if item.get("verdict") == "lure":
                    cats_data[cat]["lured"] += 1
        beh_7cat_raw[mk] = {
            cat: round(v["lured"] / v["conflict"] * 100) if v["conflict"] else 0
            for cat, v in cats_data.items()
        }

    # Qwen 7-cat rates from behavioral_complete
    beh_complete = load_json(BEHAVIORAL_7CAT)
    for mk in ["qwen_nothink", "qwen_think"]:
        if mk in beh_complete["models"]:
            beh_7cat_raw[mk] = {}
            for cat, info in beh_complete["models"][mk]["categories"].items():
                if info is not None:
                    beh_7cat_raw[mk][cat] = round(info["lure_rate"] * 100)

    # Paper Table 1 values (as they appear in the tex)
    paper_table1 = {
        "llama": {
            "base_rate": 84, "conjunction": 55, "syllogism": 52,
            "loss_aversion": 0, "sunk_cost": 0, "certainty_effect": 0,
            "availability": 13, "crt": 0, "arithmetic": 0, "framing": 0,
            "anchoring": 0,
        },
        "r1_distill": {
            "base_rate": 4, "conjunction": 0, "syllogism": 0,
            "loss_aversion": 0, "sunk_cost": 0, "certainty_effect": 0,
            "availability": 0, "crt": 3, "arithmetic": 0, "framing": 0,
            "anchoring": 10,
        },
        "qwen_nothink": {
            "base_rate": 56, "conjunction": 95, "syllogism": 0,
            "loss_aversion": 0, "sunk_cost": 0, "certainty_effect": 0,
            "availability": 0, "crt": 0, "arithmetic": 0, "framing": 0,
            "anchoring": 10,
        },
        "qwen_think": {
            "base_rate": 4, "conjunction": 55, "syllogism": 0,
            "loss_aversion": 0, "sunk_cost": 0, "certainty_effect": 0,
            "availability": 0, "crt": 0, "arithmetic": 0, "framing": 0,
            "anchoring": 0,
        },
        "olmo_instruct": {
            "base_rate": 46, "conjunction": 50, "syllogism": 0,
            "loss_aversion": 33, "crt": 3, "arithmetic": 0, "framing": 0,
            "anchoring": 5,
        },
        "olmo_think": {
            "base_rate": 0, "conjunction": 0, "syllogism": 4,
            "loss_aversion": 0, "crt": 3, "arithmetic": 0, "framing": 0,
            "anchoring": 0,
        },
    }

    # Check each model's per-category rates against the CORRECT data source
    for mk in paper_table1:
        for cat, paper_val in paper_table1[mk].items():
            # Determine correct data source
            if mk in ("olmo_instruct", "olmo_think"):
                # OLMo always uses 470-item data
                data_cats = canonical["behavioral"].get(mk, {}).get("per_category_470", {})
                source = "470-item"
            elif cat in ORIGINAL_7_CATS and mk in beh_7cat_raw:
                # Original 7 categories: use 7-cat raw files
                data_val = beh_7cat_raw[mk].get(cat)
                if data_val is not None and paper_val != data_val:
                    mismatches.append(Mismatch(
                        3, "CRITICAL", f"Table 1: {mk}/{cat}",
                        find_line("tab:behavioral", paper_lines),
                        f"{mk} {cat} lure rate = {paper_val}%",
                        f"7-category data shows {data_val}%",
                        f"Update Table 1 {mk} {cat} from {paper_val}% to {data_val}%",
                    ))
                continue
            elif cat in NEW_4_CATS:
                # New categories: use 470-item data
                data_cats = canonical["behavioral"].get(mk, {}).get("per_category_470", {})
                source = "470-item"
            else:
                continue

            if cat in data_cats:
                data_val = int(data_cats[cat]["lure_rate_pct"])
                if paper_val != data_val:
                    mismatches.append(Mismatch(
                        3, "CRITICAL", f"Table 1: {mk}/{cat}",
                        find_line("tab:behavioral", paper_lines),
                        f"{mk} {cat} lure rate = {paper_val}%",
                        f"{source} data shows {data_val}%",
                        f"Update Table 1 {mk} {cat} from {paper_val}% to {data_val}%",
                    ))

    # Check headline overall rates from the paper
    # Paper says: Llama 27.3%, R1 2.4%, Qwen no-think 21.0%, Qwen think 7.0%
    headline_checks = [
        ("llama", 27.3, "27.3"),
        ("r1_distill", 2.4, "2.4"),
        ("qwen_nothink", 21.0, "21.0"),
        ("qwen_think", 7.0, "7.0"),
    ]
    for mk, paper_rate, paper_str in headline_checks:
        data_overall = canonical["behavioral"].get(mk, {}).get("overall_7cat_raw", {})
        if data_overall:
            data_rate = data_overall["lure_rate_pct"]
            if abs(paper_rate - data_rate) > 0.2:
                mismatches.append(Mismatch(
                    3, "CRITICAL", f"Main paper headline overall rate: {mk}",
                    find_line(paper_str, paper_lines),
                    f"Paper says {mk} overall = {paper_rate}%",
                    f"Raw data: {data_rate}% ({data_overall['source']})",
                    f"Update to {data_rate}%",
                ))

    # Check OLMo overall rates
    for olmo_key, paper_rate in [("olmo_instruct", 14.9), ("olmo_think", 0.9)]:
        data_rate = canonical["behavioral"][olmo_key]["overall_470"]["lure_rate_pct"]
        if abs(paper_rate - data_rate) > 0.15:
            mismatches.append(Mismatch(
                3, "CRITICAL", f"Main paper OLMo overall rate",
                find_line(f"{paper_rate}", paper_lines),
                f"{olmo_key} overall = {paper_rate}%",
                f"Data shows {data_rate}%",
                f"Update to {data_rate}%",
            ))

    # Check OLMo per-category rates against supplementary claims
    # The consistency check (#3) says supplementary shows 0% for OLMo everywhere,
    # but the raw data shows non-zero rates. The supplementary is WRONG.
    olmo_inst_data = canonical["behavioral"]["olmo_instruct"]["per_category_470"]
    olmo_think_data = canonical["behavioral"]["olmo_think"]["per_category_470"]

    # Report OLMo discrepancies vs supplementary
    olmo_inst_nonzero = {cat: v for cat, v in olmo_inst_data.items()
                         if v["lure_rate_pct"] > 0}
    olmo_think_nonzero = {cat: v for cat, v in olmo_think_data.items()
                          if v["lure_rate_pct"] > 0}

    if olmo_inst_nonzero:
        cats_str = ", ".join(
            f"{c}={int(v['lure_rate_pct'])}%" for c, v in olmo_inst_nonzero.items()
        )
        mismatches.append(Mismatch(
            3, "CRITICAL", "Supplementary Section H vs. raw data",
            None,
            "Supplementary claims OLMo Instruct has 0% lure rate across ALL categories",
            f"Raw data: OLMo Instruct non-zero in: {cats_str}",
            "Rewrite Supplementary Section H with correct OLMo behavioral data",
        ))

    if olmo_think_nonzero:
        cats_str = ", ".join(
            f"{c}={int(v['lure_rate_pct'])}%" for c, v in olmo_think_nonzero.items()
        )
        mismatches.append(Mismatch(
            3, "CRITICAL", "Supplementary Section H vs. raw data",
            None,
            "Supplementary claims OLMo Think has 0% lure rate across ALL categories",
            f"Raw data: OLMo Think non-zero in: {cats_str}",
            "Rewrite Supplementary Section H with correct OLMo behavioral data",
        ))

    # #4: OLMo probe summary vs layer-by-layer data
    # Bootstrap data is the truth.
    olmo_inst_vuln = olmo_inst_boot["peak_vulnerable"]
    olmo_think_vuln = olmo_think_boot["peak_vulnerable"]

    # Paper says OLMo Instruct: 0.996 at L24, OLMo Think: 0.962 at L22
    paper_olmo_inst = {"auc": 0.996, "layer": 24, "ci": "[0.988, 1.000]"}
    paper_olmo_think = {"auc": 0.962, "layer": 22, "ci": "[0.934, 0.982]"}

    for label, paper_vals, data_vals in [
        ("OLMo Instruct", paper_olmo_inst, olmo_inst_vuln),
        ("OLMo Think", paper_olmo_think, olmo_think_vuln),
    ]:
        data_auc = round3(data_vals["auc"])
        if abs(paper_vals["auc"] - data_auc) > 0.002:
            mismatches.append(Mismatch(
                4, "MODERATE", f"Table 2: {label} peak AUC",
                find_line("tab:probe_summary", paper_lines),
                f"{label} peak AUC = {paper_vals['auc']}",
                f"Bootstrap data: {data_auc} (raw: {data_vals['auc']:.4f})",
                f"Update to {data_auc}",
            ))
        if paper_vals["layer"] != data_vals["layer"]:
            mismatches.append(Mismatch(
                4, "MODERATE", f"Table 2: {label} peak layer",
                find_line("tab:probe_summary", paper_lines),
                f"{label} peak at L{paper_vals['layer']}",
                f"Bootstrap data: L{data_vals['layer']}",
                f"Update to L{data_vals['layer']}",
            ))

    # The supplementary's layer-by-layer table will show CV values, not bootstrap.
    # This is the source of #4's internal inconsistency. The fix is to clarify
    # that the summary table uses bootstrap and the layer table uses CV.
    mismatches.append(Mismatch(
        4, "STRUCTURAL", "Supplementary: OLMo summary table vs layer-by-layer table",
        None,
        "Summary table (Table H.2) uses bootstrap CIs; layer-by-layer table uses CV means",
        "These are different methodologies, creating apparent inconsistency",
        ("Add a note to supplementary: 'Summary values are bootstrap means with "
         "1000-resample CIs; per-layer values are 5-fold CV means.'"),
    ))

    # #5: Control AUC ceiling
    # Paper says <= 0.55. Bootstrap data shows max control:
    llama_max_ctrl = llama_boot.get("max_control_vulnerable", {}).get("control_auc", 0)
    r1_max_ctrl = r1_boot.get("max_control_vulnerable", {}).get("control_auc", 0)
    overall_max_ctrl = max(llama_max_ctrl, r1_max_ctrl)
    # Also check OLMo
    olmo_inst_max_ctrl = olmo_inst_boot.get("max_control_vulnerable", {}).get("control_auc", 0)
    olmo_think_max_ctrl = olmo_think_boot.get("max_control_vulnerable", {}).get("control_auc", 0)
    global_max_ctrl = max(overall_max_ctrl, olmo_inst_max_ctrl, olmo_think_max_ctrl)

    paper_ctrl_ceiling = 0.55
    if global_max_ctrl > paper_ctrl_ceiling + 0.01:
        mismatches.append(Mismatch(
            5, "CRITICAL", "Main paper, selectivity paragraph",
            find_line("0.55", paper_lines),
            f"Control probes achieve AUC <= {paper_ctrl_ceiling}",
            (f"Max control AUC across all models/layers: {global_max_ctrl:.3f} "
             f"(Llama: {llama_max_ctrl:.3f}, R1: {r1_max_ctrl:.3f}, "
             f"OLMo-Inst: {olmo_inst_max_ctrl:.3f}, OLMo-Think: {olmo_think_max_ctrl:.3f})"),
            f"Update to '<= {round(global_max_ctrl + 0.01, 2):.2f}' or '<= 0.66'",
        ))

    # #6: Selectivity claim (> 40pp)
    llama_sel = llama_vuln.get("selectivity", 0)
    r1_sel = r1_vuln.get("selectivity", 0)
    paper_sel_claim = 0.40  # "> 40 percentage points"

    selectivity_details = (
        f"Llama L{llama_vuln['layer']}: sel={llama_sel:.4f} "
        f"(AUC={llama_vuln['auc']:.4f} - ctrl={llama_vuln['control_auc']:.4f}), "
        f"R1 L{r1_vuln['layer']}: sel={r1_sel:.4f} "
        f"(AUC={r1_vuln['auc']:.4f} - ctrl={r1_vuln['control_auc']:.4f})"
    )

    if llama_sel < paper_sel_claim or r1_sel < paper_sel_claim:
        mismatches.append(Mismatch(
            6, "CRITICAL", "Main paper, selectivity paragraph",
            find_line("40 percentage points", paper_lines),
            "Selectivity exceeds 40 percentage points at peak layers for both models",
            f"Bootstrap data: {selectivity_details}",
            (f"Update to '>= {round(min(llama_sel, r1_sel) * 100, 0):.0f} percentage points' "
             f"or state the exact values"),
        ))

    # Paper Table 2 says Llama selectivity = 0.434, R1 = 0.410
    # These don't match bootstrap either
    paper_table2_llama_sel = 0.434
    paper_table2_r1_sel = 0.410
    if abs(paper_table2_llama_sel - llama_sel) > 0.005:
        mismatches.append(Mismatch(
            6, "CRITICAL", "Table 2: Llama selectivity",
            find_line("0.434", paper_lines),
            f"Table 2 Llama selectivity = {paper_table2_llama_sel}",
            f"Bootstrap: {llama_sel:.4f}",
            f"Update to {round3(llama_sel)}",
        ))
    if abs(paper_table2_r1_sel - r1_sel) > 0.005:
        mismatches.append(Mismatch(
            6, "CRITICAL", "Table 2: R1 selectivity",
            find_line("0.410", paper_lines),
            f"Table 2 R1 selectivity = {paper_table2_r1_sel}",
            f"Bootstrap: {r1_sel:.4f}",
            f"Update to {round3(r1_sel)}",
        ))

    # Paper Table 2 control AUC: Llama 0.54, R1 0.52
    paper_llama_ctrl = 0.54
    paper_r1_ctrl = 0.52
    data_llama_ctrl = llama_vuln["control_auc"]
    data_r1_ctrl = r1_vuln["control_auc"]
    if abs(paper_llama_ctrl - data_llama_ctrl) > 0.02:
        mismatches.append(Mismatch(
            5, "CRITICAL", "Table 2: Llama control AUC",
            find_line("0.54", paper_lines),
            f"Table 2 Llama control AUC = {paper_llama_ctrl}",
            f"Bootstrap at peak layer: {data_llama_ctrl:.4f}",
            f"Update to {round(data_llama_ctrl, 2)}",
        ))
    if abs(paper_r1_ctrl - data_r1_ctrl) > 0.02:
        mismatches.append(Mismatch(
            5, "CRITICAL", "Table 2: R1 control AUC",
            find_line("0.52", paper_lines),
            f"Table 2 R1 control AUC = {paper_r1_ctrl}",
            f"Bootstrap at peak layer: {data_r1_ctrl:.4f}",
            f"Update to {round(data_r1_ctrl, 2)}",
        ))

    # #7-#8: Missing supplementary sections (structural)
    if supp_text:
        # #7: Natural frequency / ecological rationality analysis
        # The supplementary MENTIONS natural frequency in the benchmark description
        # but does NOT have a dedicated results section analyzing the outcomes.
        # Look for a section header or results table for natural frequency.
        has_nat_freq_results = any(
            marker in supp_text.lower()
            for marker in [
                "natural frequency results",
                "ecological rationality results",
                "frequency framing results",
                "section k",  # Expected section for this
                "84\\% $\\to$ 100\\%",  # The actual numbers from main paper
            ]
        )
        if not has_nat_freq_results:
            mismatches.append(Mismatch(
                7, "STRUCTURAL", "Supplementary",
                None,
                ("Main paper says 'Full analysis is in the supplementary material' "
                 "for natural frequency / ecological rationality results"),
                ("Supplementary mentions natural frequency in benchmark description "
                 "but has NO dedicated results section"),
                "Add Section K with ecological rationality analysis, or remove the claim",
            ))

        # #8: Check for the 4 additional categories complete results
        # The supplementary needs to report results for ALL of:
        # loss_aversion, sunk_cost, certainty_effect, availability
        has_loss_aversion_results = "loss aversion" in supp_text.lower() and any(
            word in supp_text.lower() for word in ["33%", "33.3%", "0.333"]
        )
        has_availability_results = "availability" in supp_text.lower() and any(
            word in supp_text.lower() for word in ["13%", "0.133"]
        )
        has_certainty_results = "certainty effect" in supp_text.lower() and "results" in supp_text.lower()

        missing_cats = []
        if not has_loss_aversion_results:
            missing_cats.append("loss aversion")
        if not has_availability_results:
            missing_cats.append("availability")
        if not has_certainty_results:
            missing_cats.append("certainty effect")

        if missing_cats:
            mismatches.append(Mismatch(
                8, "STRUCTURAL", "Supplementary",
                None,
                ("Main paper says 4 additional categories (loss aversion, sunk cost, "
                 "certainty effect, availability) are reported in supplementary"),
                f"Missing results for: {', '.join(missing_cats)}",
                "Add supplementary section with complete results, or remove the claim",
            ))

    # #9-#10: Category count mismatch
    # Main paper: "7 categories, 165 pairs, 330 items" (primary set)
    # Supplementary: "8 categories, 190 pairs, 380 items"
    # Truth from data: 7 original categories (330 items), 4 additional (140 items)
    # Total: 11 categories, 235 pairs, 470 items
    if supp_text and "8 categories" in supp_text:
        mismatches.append(Mismatch(
            9, "MODERATE", "Supplementary A.1 vs. main paper",
            None,
            "Supplementary says '380 items across 8 categories form the primary set'",
            ("Data has 7 original categories (330 items, 165 pairs) + 4 new = 11 total. "
             "The '8' likely includes sunk_cost but not the other 3."),
            ("Align: either 7 (original) or 11 (all). The main paper says 7, "
             "which matches the probe analyses. Fix supplementary to say 7."),
        ))

    if supp_text and "3 additional categories" in supp_text:
        mismatches.append(Mismatch(
            10, "MODERATE", "Supplementary A.1 vs. main paper",
            None,
            "Supplementary says '3 additional categories' (nat freq, sunk cost, contamination)",
            "Main paper says '4 additional' (sunk cost, loss aversion, certainty, availability)",
            ("These are different categorization schemes. Align on the 4-category "
             "extension (sunk cost, loss aversion, certainty effect, availability). "
             "Natural frequency is a variant of base rate, not a separate category."),
        ))

    # #11: Transfer matrix and cross-prediction use L14 but paper claims peak at L16
    # This is CORRECT behavior: cross-prediction used the CV pipeline's peak (L14),
    # not the bootstrap peak (L16). But paper must be clear about this.
    llama_cp_l14 = canonical["cross_prediction"]["llama"]["layers"].get(14, {})
    if llama_cp_l14:
        # Paper references L14 for cross-prediction but claims peak is L16 (bootstrap).
        # L14 is the CV peak. The paper should clarify which is which.
        xpred_line = find_line("(L14)", paper_lines)
        peak_line = find_line("L16", paper_lines)
        if xpred_line and peak_line:
            mismatches.append(Mismatch(
                11, "MODERATE", "Main paper cross-prediction vs. probing section",
                xpred_line,
                ("Cross-prediction uses L14 (line ~510) but probing section claims "
                 "peak is L16 (line ~408). Both are correct but from different methods."),
                ("L14 is the 5-fold CV peak (330 items, ALL categories); "
                 "L16 is the bootstrap peak (160 vulnerable items only). "
                 "Cross-prediction was run at L14."),
                ("Add qualifier: 'At layer 14 (the peak layer in 5-fold "
                 "cross-validation; see Section~C)' to avoid contradiction "
                 "with the bootstrap peak of L16 reported above."),
            ))

    # #12: Cross-prediction transfer AUC 0.378 -- confirmed correct at L14
    # No mismatch, but note the layer attribution
    if llama_cp_l14.get("transfer_to_immune"):
        data_val = llama_cp_l14["transfer_to_immune"]
        if abs(data_val - 0.378) > 0.002:
            mismatches.append(Mismatch(
                12, "CRITICAL", "Cross-prediction transfer AUC",
                find_line("0.378", paper_lines),
                "Paper says transfer AUC = 0.378 at L14",
                f"Data: {data_val:.4f} at L14",
                f"Update to {round3(data_val)}",
            ))

    # #13: R1-Distill L4 transfer AUC 0.878 -- check
    r1_cp_l4 = canonical["cross_prediction"]["r1_distill"]["layers"].get(4, {})
    if r1_cp_l4.get("transfer_to_immune"):
        data_val = r1_cp_l4["transfer_to_immune"]
        if abs(data_val - 0.878) > 0.002:
            mismatches.append(Mismatch(
                13, "CRITICAL", "R1-Distill L4 transfer AUC",
                find_line("0.878", paper_lines),
                "Paper says R1-Distill transfer AUC = 0.878 at L4",
                f"Data: {data_val:.4f}",
                f"Update to {round3(data_val)}",
            ))

    # #14: Attention heads 57 vs 30 -- verified consistent, no check needed

    # ---- Additional checks not in the original 14 ----

    # Check cross-model transfer numbers
    cm_l2r = canonical["cross_model_transfer"]["llama_to_r1"]
    cm_r2l = canonical["cross_model_transfer"]["r1_to_llama"]

    paper_l2r = 0.920
    paper_r2l = 0.954
    if abs(paper_l2r - cm_l2r["peak_auc"]) > 0.002:
        mismatches.append(Mismatch(
            0, "MODERATE", "Cross-model transfer Llama->R1",
            find_line("0.920", paper_lines),
            f"Paper says Llama->R1 = {paper_l2r}",
            f"Data: {cm_l2r['peak_auc']} at L{cm_l2r['peak_layer']}",
            f"Update to {cm_l2r['peak_auc']}",
        ))
    if abs(paper_r2l - cm_r2l["peak_auc"]) > 0.002:
        mismatches.append(Mismatch(
            0, "MODERATE", "Cross-model transfer R1->Llama",
            find_line("0.954", paper_lines),
            f"Paper says R1->Llama = {paper_r2l}",
            f"Data: {cm_r2l['peak_auc']} at L{cm_r2l['peak_layer']}",
            f"Update to {cm_r2l['peak_auc']}",
        ))

    # Check the Qwen overall rates in paper (21% and 7%)
    # From behavioral_470: qwen_nothink = 19.1%, qwen_think = 9.4%
    # From behavioral_complete (earlier data, 190 conflict):
    # Need to check what the paper's 21% and 7% come from
    qwen_nt_470 = canonical["behavioral"].get("qwen_nothink", {}).get("overall_470", {})
    qwen_t_470 = canonical["behavioral"].get("qwen_think", {}).get("overall_470", {})

    # The paper says Qwen no-think = 21.0%, think = 7.0%
    # Those come from the 7-cat subset (behavioral_complete)
    # Let's check behavioral_complete for Qwen
    beh_7cat_data = load_json(BEHAVIORAL_7CAT)
    beh_7cat_models = beh_7cat_data.get("models", {})
    if "qwen_nothink" in beh_7cat_models:
        qwen_nt_7cat = beh_7cat_models["qwen_nothink"]["overall"]
        paper_qwen_nt_rate = 21.0
        data_qwen_nt_rate = round(qwen_nt_7cat["lure_rate"] * 100, 1)
        if abs(paper_qwen_nt_rate - data_qwen_nt_rate) > 0.2:
            mismatches.append(Mismatch(
                3, "MODERATE", "Qwen no-think overall rate",
                find_line("21", paper_lines),
                f"Paper says Qwen no-think = {paper_qwen_nt_rate}%",
                f"7-cat data: {data_qwen_nt_rate}%, 470-item data: {qwen_nt_470.get('lure_rate_pct', '?')}%",
                "Clarify which dataset, or update to match the 7-cat value",
            ))
    if "qwen_think" in beh_7cat_models:
        qwen_t_7cat = beh_7cat_models["qwen_think"]["overall"]
        paper_qwen_t_rate = 7.0
        data_qwen_t_rate = round(qwen_t_7cat["lure_rate"] * 100, 1)
        if abs(paper_qwen_t_rate - data_qwen_t_rate) > 0.2:
            mismatches.append(Mismatch(
                3, "MODERATE", "Qwen think overall rate",
                find_line("7.0", paper_lines),
                f"Paper says Qwen think = {paper_qwen_t_rate}%",
                f"7-cat data: {data_qwen_t_rate}%, 470-item data: {qwen_t_470.get('lure_rate_pct', '?')}%",
                "Clarify which dataset, or update to match the 7-cat value",
            ))

    # Check that R1 per-category rates in paper match 7-cat data for the
    # categories that were in both the _ALL and _470 files
    # Paper Table 1 says R1 CRT=3%, anchoring=10%.
    # 7-cat (llama_ALL/r1_distill_ALL): CRT=3.3%, anchoring=10%
    # 470-item: CRT=16.7%, anchoring=15%
    # The paper rounds 3.3->3 and 10->10, using the 7-cat data for Llama/R1
    # but 470 data for the extended categories

    # Flag the fact that R1 per-category rates differ between 7-cat and 470
    r1_7cat_cats = beh_7cat_models.get("r1_distill", {}).get("categories", {})
    r1_470_cats = canonical["behavioral"].get("r1_distill", {}).get("per_category_470", {})
    for cat in ["crt", "anchoring"]:
        if cat in r1_7cat_cats and r1_7cat_cats[cat] is not None:
            rate_7 = round(r1_7cat_cats[cat]["lure_rate"] * 100, 1)
            rate_470 = r1_470_cats.get(cat, {}).get("lure_rate_pct", "?")
            if isinstance(rate_470, (int, float)) and abs(rate_7 - rate_470) > 1:
                # The 470 set has MORE items than the 7-cat set, so rates may differ
                pass  # Not a bug, different sample sizes

    return mismatches


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> None:
    print("=" * 72)
    print("  S1/S2 Number Reconciliation")
    print("=" * 72)

    # Build canonical numbers
    print("\n[1/3] Building canonical numbers from data files...")
    canonical = build_canonical()

    # Write canonical numbers
    CANONICAL_OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(CANONICAL_OUT, "w") as f:
        json.dump(canonical, f, indent=2, default=str)
    print(f"  Written to: {CANONICAL_OUT}")

    # Check paper
    print("\n[2/3] Checking paper against canonical numbers...")
    mismatches = check_paper(canonical)

    # Report
    print(f"\n[3/3] Found {len(mismatches)} mismatches:\n")

    by_severity = defaultdict(list)
    for m in mismatches:
        by_severity[m.severity].append(m)

    for severity in ["CRITICAL", "MODERATE", "STRUCTURAL"]:
        items = by_severity.get(severity, [])
        if not items:
            continue
        print(f"\n{'='*72}")
        print(f"  {severity} ({len(items)} issues)")
        print(f"{'='*72}")
        for m in items:
            print(f"\n{m}")

    # Summary table
    print(f"\n\n{'='*72}")
    print("  SUMMARY: Key canonical values for the paper")
    print(f"{'='*72}")

    b = canonical["probes_bootstrap"]
    print("\nProbe results (bootstrap, 1000 resamples, vulnerable categories):")
    for mk in ["llama", "r1_distill", "olmo_instruct", "olmo_think"]:
        v = b[mk]["peak_vulnerable"]
        ctrl_str = f", ctrl={v.get('control_auc', '?')}, sel={v.get('selectivity', '?')}" if "control_auc" in v else ""
        print(f"  {mk:20s}: L{v['layer']:2d}  AUC={v['auc']:.4f}  [{v['ci_lower']:.4f}, {v['ci_upper']:.4f}]{ctrl_str}")

    mc = b["llama"].get("max_control_vulnerable", {})
    print(f"\n  Max control AUC (Llama): L{mc.get('layer', '?')} = {mc.get('control_auc', '?')}")
    mc_r1 = b["r1_distill"].get("max_control_vulnerable", {})
    print(f"  Max control AUC (R1):    L{mc_r1.get('layer', '?')} = {mc_r1.get('control_auc', '?')}")
    mc_oi = b["olmo_instruct"].get("max_control_vulnerable", {})
    print(f"  Max control AUC (OLMo-I): L{mc_oi.get('layer', '?')} = {mc_oi.get('control_auc', '?')}")
    mc_ot = b["olmo_think"].get("max_control_vulnerable", {})
    print(f"  Max control AUC (OLMo-T): L{mc_ot.get('layer', '?')} = {mc_ot.get('control_auc', '?')}")

    print("\nProbe results (5-fold CV, 330 items, ALL categories):")
    for mk, info in canonical["probes_cv"].items():
        print(f"  {mk:20s}: L{info['best_layer']:2d}  AUC={info['best_auc']:.4f}")

    print("\nBehavioral (paper headline rates from raw _ALL / behavioral_complete):")
    for mk, info in canonical["behavioral"].items():
        if "overall_7cat_raw" in info:
            o = info["overall_7cat_raw"]
            print(f"  {mk:20s}: {o['n_lure']}/{o['n_conflict']} = {o['lure_rate_pct']}%  ({o.get('source', '')})")

    print("\nBehavioral (11-category, 235 conflict pairs -- per-category rates):")
    for mk, info in canonical["behavioral"].items():
        if "overall_470" in info:
            o = info["overall_470"]
            print(f"  {mk:20s}: {o['n_lure']}/{o['n_conflict']} = {o['lure_rate_pct']}%")

    print("\nCross-model transfer:")
    for d, info in canonical["cross_model_transfer"].items():
        print(f"  {d:20s}: L{info['peak_layer']}  AUC={info['peak_auc']}")

    print("\nCross-prediction at L14 (Llama):")
    cp = canonical["cross_prediction"]["llama"]["layers"]
    print(f"  Within vulnerable:  {cp[14]['within_vulnerable']}")
    print(f"  Transfer to immune: {cp[14]['transfer_to_immune']}")

    # Final verdict
    n_critical = len(by_severity.get("CRITICAL", []))
    n_moderate = len(by_severity.get("MODERATE", []))
    n_structural = len(by_severity.get("STRUCTURAL", []))
    print(f"\n{'='*72}")
    print(f"  TOTAL: {n_critical} CRITICAL, {n_moderate} MODERATE, {n_structural} STRUCTURAL")
    print(f"{'='*72}")

    if n_critical > 0:
        print("\nACTION REQUIRED: Fix critical mismatches before submission.")
        sys.exit(1)
    else:
        print("\nAll critical checks pass.")
        sys.exit(0)


if __name__ == "__main__":
    main()
